<?php
$b2sLastVersion = get_option('b2s_plugin_version');
?>
<!-- Sidebar|Start -Include-->
<div class="col-md-3 col-xs-12 del-padding-left del-padding-right pull-right b2s-sidebar hidden-xs hidden-sm">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-md-12 del-padding-right">
                <div class="row">
                    <div class="media">
                        <div class="col-md-2 del-padding-left">
                            <a class="" href="https://www.blog2social.com" target="_blank">
                                <img class="img-responsive b2s-img-logo" src="<?php echo plugins_url('/assets/images/b2s@64.png', B2S_PLUGIN_FILE); ?>" alt="logo">
                            </a>
                        </div>
                        <div class="col-md-10 del-padding-left">
                            <div class="media-body">
                                <a href="https://www.blog2social.com" class="b2s-btn-logo" target="_blank"><?php _e("Blog2Social", "blog2social") ?></a> 
                                <span class="b2s-sidebar-version padding-left-5"><?php echo ($b2sLastVersion !== false) ? __("Version", "blog2social") . ' ' . B2S_Util::getVersion($b2sLastVersion) : ''; ?> </span>
                                <br>
                                <div class="b2s-sidebar-licence padding-left-5"><?php _e("Licence", "blog2social") ?>:
                                    <a href="admin.php?page=blog2social-premium" class="b2s-sidebar-btn-licence b2s-key-name">
                                        <?php
                                        $versionType = unserialize(B2S_PLUGIN_VERSION_TYPE);
                                        if (defined("B2S_PLUGIN_TRAIL_END") && strtotime(B2S_PLUGIN_TRAIL_END) > time()) {
                                            echo 'FREE-TRIAL (' . $versionType[B2S_PLUGIN_USER_VERSION] . ')';
                                        } else {
                                            echo $versionType[B2S_PLUGIN_USER_VERSION];
                                        }
                                        ?><i class="b2s-sidebar-licence-btn-edit glyphicon glyphicon-pencil"></i>
                                    </a>  
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cleardfix"></div>
            <div class="col-md-12">
                <div class="row">
                    <hr>
                    <div class="b2s-sidebar-head">
                        <div class="b2s-sidebar-head-text">
                            <?php _e("Blog Content", "blog2social") ?>
                        </div>
                        <ul>
                            <li class="b2s-list-margin-left-10">
                                <i class="glyphicon glyphicon-th-list glyphicon-success"></i> <a href="admin.php?page=blog2social-post" class="b2s-sidebar-menu-item"><?php _e("Share Blog Post", "blog2social") ?></a> 
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="cleardfix"></div>
            <div class="col-md-12">
                <div class="row">
                    <hr>
                    <div class="b2s-sidebar-head">
                        <div class="b2s-sidebar-head-text">
                            <?php _e("Content Curation", "blog2social") ?>
                        </div>
                        <ul>
                            <li class="b2s-list-margin-left-10">
                                <i class="glyphicon glyphicon-plus glyphicon-success"></i> <a href="admin.php?page=blog2social-curation" class="b2s-sidebar-menu-item"><?php _e("Create Post", "blog2social") ?></a> 
                            </li>
			    <li class="b2s-list-margin-left-10">
                                <i class="glyphicon glyphicon-th-list glyphicon-success"></i> <a href="admin.php?page=blog2social-curation-draft" class="b2s-sidebar-menu-item"><?php _e('Drafts', 'blog2social') ?></a> 
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="cleardfix"></div>
            <div class="col-md-12">
                <div class="row">
                    <hr>
                    <div class="b2s-sidebar-head">
                        <div class="b2s-sidebar-head-text">
                            <?php _e("Content Library", "blog2social") ?>
                        </div>
                        <ul>
                            <li class="b2s-list-margin-left-10">
                                <i class="glyphicon glyphicon-th-list glyphicon-success"></i> <a href="admin.php?page=blog2social-post" class="b2s-sidebar-menu-item"><?php _e("all Posts", "blog2social") ?></a> 
                            </li>
                            <li class="b2s-list-margin-left-10">
                                <i class="glyphicon glyphicon-th-list glyphicon-success"></i> <a href="admin.php?page=blog2social-approve" class="b2s-sidebar-menu-item"><?php _e("Instant Sharing", "blog2social") ?></a> 
                            </li>
                            <li class="b2s-list-margin-left-10">
                                <i class="glyphicon glyphicon-time glyphicon-success"></i> <a href="admin.php?page=blog2social-sched" class="b2s-sidebar-menu-item"><?php _e("Scheduled Posts", "blog2social") ?></a> 
                            </li>
                            <li class="b2s-list-margin-left-10">
                                <i class="glyphicon glyphicon-th-list glyphicon-success"></i> <a href="admin.php?page=blog2social-publish" class="b2s-sidebar-menu-item"><?php _e("Shared Posts", "blog2social") ?></a> 
                            </li>
                            <li class="b2s-list-margin-left-10">
                                <i class="glyphicon glyphicon-calendar glyphicon-success"></i> <a href="admin.php?page=blog2social-calendar" class="b2s-sidebar-menu-item"><?php _e("Calendar", "blog2social") ?></a> 
                            </li>
                        </ul>
                        <hr>
                        <ul>
                            <li class="b2s-list-margin-left-10">
                                <i class="glyphicon glyphicon-user glyphicon-success"></i> <a href="admin.php?page=blog2social-network" class="b2s-sidebar-menu-item"><?php _e("Social Accounts", "blog2social") ?></a> 
                            </li>
                            <li class="b2s-list-margin-left-10">
                                <i class="glyphicon glyphicon-th-list glyphicon-success"></i> <a href="admin.php?page=blog2social-settings" class="b2s-sidebar-menu-item"><?php _e("Settings", "blog2social") ?></a> 
                            </li>
                            <li class="b2s-list-margin-left-10">
                                <i class="glyphicon glyphicon-question-sign glyphicon-success"></i> <a href="admin.php?page=blog2social-support" class="b2s-sidebar-menu-item"><?php _e("Help & Support", "blog2social") ?></a> 
                            </li>
                            <li class="b2s-list-margin-left-10">
                                <i class="glyphicon glyphicon-pencil glyphicon-success"></i> <a href="admin.php?page=blog2social-premium" class="b2s-sidebar-menu-item"><?php _e("Upgrade Licence", "blog2social") ?></a> 
                            </li>
                            <li class="b2s-list-margin-left-10">
                                <i class="glyphicon glyphicon-signal glyphicon-success"></i> <a href="<?php echo B2S_Tools::getSupportLink('affiliate'); ?>" target="_blank" class="b2s-sidebar-menu-item"><?php _e("Plans & Prices", "blog2social") ?></a> 
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="cleardfix"></div>
            <div class="col-md-12">
                <div class="row">
                    <hr>
                    <div class="b2s-sidebar-head">
                        <div class="b2s-sidebar-head-text">
                            <span class="glyphicon glyphicon-star glyphicon-success"></span> <?php _e("Rate it!", "blog2social"); ?> 
                        </div>
                        <p><?php _e("If you like Blog2Social, please give us a 5 star rating. If there is anything that does not work for you, please contact us!", "blog2social"); ?></p>
                        <a target="_blank" href="https://wordpress.org/support/plugin/blog2social/reviews/" class="btn btn-success btn-block"><?php _e("RATE BLOG2SOCIAL", "blog2social") ?></a>
                    </div>
                </div>
            </div>

            <div class="cleardfix"></div>
            <div class="col-md-12">
                <div class="row">
                    <br>
                    <hr>
                    <div class="b2s-sidebar-head">
                        <div class="b2s-sidebar-head-text">
                            <span class="glyphicon glyphicon-bullhorn glyphicon-success"></span> <?php _e("Blog2Social Blog News", "blog2social"); ?> 
                        </div>
                        <p> <ul><?php echo B2S_Notice::getBlogEntries(substr(B2S_LANGUAGE, 0, 2)); ?></ul></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Sidebar|End-->


