<!--Header-->
<?php
$wpUserData = wp_get_current_user();
$meta = B2S_Meta::getInstance();
$generalOptions = get_option('B2S_PLUGIN_GENERAL_OPTIONS');
$b2sActive = $meta->is_b2s_active();
$showYoast = ($_GET['page'] == 'blog2social-settings' && $meta->is_yoast_seo_active() && $b2sActive) ? 'block' : 'none';
$showAioseop = ($meta->is_aioseop_active() && $b2sActive) ? 'block' : 'none';
$showWebdaos = ($meta->is_webdados_active() && $b2sActive) ? 'block' : 'none';

$options = new B2S_Options(B2S_PLUGIN_BLOG_USER_ID);
$autoPostLimit = 'none';
$autoPostCon = $options->_getOption('auto_post_import_condition');
if ($autoPostCon !== false && is_array($autoPostCon) && isset($autoPostCon['count'])) {
    $con = unserialize(B2S_PLUGIN_AUTO_POST_LIMIT);
    $autoPostLimit = ($autoPostCon['count'] == $con[B2S_PLUGIN_USER_VERSION]) ? 'block' : 'none';
}

$b2sPrivacyPolicy = get_option('B2S_PLUGIN_PRIVACY_POLICY_USER_ACCEPT_' . B2S_PLUGIN_BLOG_USER_ID);
$showPrivacyPolicy = false;
if ($b2sPrivacyPolicy !== false) {
    $b2sPrivacyPolicy = unserialize(base64_decode($b2sPrivacyPolicy));
    if (is_array($b2sPrivacyPolicy) && $b2sPrivacyPolicy !== false && isset($b2sPrivacyPolicy[substr(B2S_LANGUAGE, 0, 2)])) {
        $showPrivacyPolicy = true;
        $b2sPrivacyPolicy = $b2sPrivacyPolicy[substr(B2S_LANGUAGE, 0, 2)];
    }
}
?>

<div class="col-md-12 del-padding-left">
    <div class="col-md-9 del-padding-left">
        <!--Info System-->
        <?php if (version_compare(phpversion(), '5.5.3', '<')) { ?>
            <div class="panel panel-group">
                <div class="panel-body">
                    <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e("To use all features of Blog2Social, PHP version 5.5.3 or higher is required. Our support assists you as of PHP version 5.5.3. See also:", "blog2social"); ?>
                    <a target="_blank" href="<?php echo ((substr(B2S_LANGUAGE, 0, 2) == 'de' || (isset($_GET['lang']) && $_GET['lang'] == 'de')) ? 'https://www.blog2social.com/de/faq/content/1/63/de/systemvoraussetzungen-fuer-die-installation-von-blog2social.html' : 'https://www.blog2social.com/en/faq/content/1/58/en/system-requirements-for-installing-blog2social.html'); ?>"><?php _e('Technical requirements for Blog2Social', 'blog2social'); ?></a>
                </div>
            </div>
        <?php } ?>

        <div class="panel panel-group b2s-network-auth-info b2s-mail-update-success" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Thank you. You\'ll now receive the blog updates from Blog2Social.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-heartbeat-fail" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('WordPress uses heartbeats by default, Blog2Social as well. Please enable heartbeats for using Blog2Social!', 'blog2social'); ?>
                <a target="_blank" href="<?php echo ((substr(B2S_LANGUAGE, 0, 2) == 'de' || (isset($_GET['lang']) && $_GET['lang'] == 'de')) ? 'https://www.blog2social.com/de/faq/content/1/63/de/systemvoraussetzungen-fuer-die-installation-von-blog2social.html' : 'https://www.blog2social.com/en/faq/content/1/58/en/system-requirements-for-installing-blog2social.html'); ?>"><?php _e('Please see FAQ', 'blog2social'); ?></a>
            </div>
        </div>
        <div class="panel panel-group b2s-server-connection-fail" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('The connection to the server failed. Try again!', 'blog2social'); ?>
            </div>
        </div>

        <!--Info Auto Post-->
        <div class="panel panel-group b2s-auto-posting" style="display: <?php echo $autoPostLimit; ?>;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('Autoposter limit has been reached', 'blog2social') ?> <br> <?php _e('Your daily limit for posting automatically has been reached.', 'blog2social'); ?>
            </div>
        </div>

        <!-- Info TOS -->
        <div class="panel panel-group b2s-tos">
            <div class="panel-body">
                <span class="glyphicon glyphicon-exclamation-sign glyphicon-info"></span> <?php _e('Google has announced to cease its consumer services of Google+ and its APIs. To help you keep on sharing content with your followers on Google+, you can now use Blog2Social Instant Sharing to share on Google+ profiles, pages and in groups.', 'blog2social') ?>
                <a href="<?php echo B2S_Tools::getSupportLink('network_tos_google_201812'); ?>" target="_blank"><?php _e('read more', 'blog2social'); ?></a>
            </div>
        </div>

        <!--Info Meta Tags -->
        <div class="panel panel-group b2s-clear-meta-tags b2s-clear-meta-tags-success" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('You have clear all page and post meta data successful.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-clear-meta-tags b2s-clear-meta-tags-error" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('The page and post meta data could not be removed.', 'blog2social'); ?>
            </div>
        </div>

        <div class="panel panel-group b2s-meta-tags-yoast b2s-meta-tags-success" style="display:<?php echo $showYoast; ?>;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('You have Yoast SEO active. Blog2Social Social Meta Tags overrides the meta tags from Yoast SEO.', 'blog2social'); ?>
            </div>
        </div>

        <div class="panel panel-group b2s-meta-tags-aioseop b2s-meta-tags-danger" style="display:<?php echo $showAioseop; ?>;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('You currently have both Blog2Social Social Meta Tags and All in One SEO Pack plugins active. To make sure that your Social Meta Tags are set correctly, please deactivate All in One Seo Social Meta settings. If they are already deactivated, you can ignore this message.', 'blog2social'); ?>
            </div>
        </div>

        <div class="panel panel-group b2s-meta-tags-webdados b2s-meta-tags-danger" style="display:<?php echo $showWebdaos; ?>;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('Blog2Social has detected another plugin that is setting Social Meta tags for your blog posts. To ensure that your Social Meta tags are set correctly for your social media posts shared with Blog2Social, please deactivate the Facebook Open Graph, Google+ and Twitter Card Tags settings in your other plugins.', 'blog2social'); ?>
            </div>
        </div>

        <!--Info-Post-->
        <div class="panel panel-group b2s-network-auth-info b2s-post-remove-fail" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('This entry could not be removed. It\'s not yours!', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-post-remove-success" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('This entry was removed successfully.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-post-edit-success" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('This post was edit successful.', 'blog2social'); ?>
            </div>
        </div>
        <?php if (isset($_GET['origin']) && $_GET['origin'] == 'save_post' && isset($_GET['postStatus'])) { ?>
            <div class="panel panel-group b2s-network-auth-info">
                <div class="panel-body">
                    <span class="glyphicon glyphicon-ok glyphicon-success"></span>
                    <?php
                    if ($_GET['postStatus'] == 'future') {
                        echo __('Post was scheduled successfully on your blog!', 'blog2social');
                    } else {
                        echo __('Post is published successfully on your blog!', 'blog2social');
                    }
                    ?>
                </div>
            </div>
        <?php } ?>

        <div class="b2s-trail-tracking" style="display: none;">
            <img height="1" width="1" style="border-style:none;" id="b2s-trail-tracking-src" alt="b2s-trail-tracking"/>
        </div>

        <!--Info-Network-->
        <div class="panel panel-group b2s-network-auth-info b2s-network-auth-success" style="display: none">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Your authorization was successful.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-network-add-mandant-success" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Your profile was saved successful.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-network-add-mandant-error" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('Your profile could not be saved.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-network-remove-fail" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('Your authorization could not be removed.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-network-remove-success" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Your authorization was removed successful.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-feedback-success" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Thank you! Your feedback has been received.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-feedback-fail" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('Your feedback could not be delivered.', 'blog2social'); ?>
            </div>
        </div>

        <!-- Info-Settings-->
        <div class="panel panel-group b2s-network-auth-info  b2s-settings-user-success" style="display:<?php echo (isset($_GET['b2s-settings-user-success']) ? 'block' : 'none'); ?>;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Your settings were successfully saved.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info  b2s-settings-user-error" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('Your settings could not be saved.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-settings-user-error-no-auth-selected" style="display:none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-remove glyphicon-danger"></span> <?php _e('Your settings could not be saved, because you have auto-posting enabled but no social networks selected.', 'blog2social'); ?>
            </div>
        </div>
        <div class="panel panel-group b2s-network-auth-info b2s-ship-settings-save" style="display: none;">
            <div class="panel-body">
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Your settings were successfully saved.', 'blog2social'); ?>
            </div>
        </div>

        <!--Rating-->
        <?php if (B2S_Rating::is_visible()) { ?>
            <div class="panel panel-group" style="border-left: 5px solid #79B232;">
                <div class="panel-body">
                    <p><?php echo str_replace("%s", B2S_Rating::count(), __("Hi, we noticed you just shared your %s. blog post with Blog2Social - that's awesome! Could you please do us a favor and give it a 5-star rating on WordPress? Just to help us spread the word and boost our motivation.", "blog2social")); ?></p>
                    <p class="b2s-notice-buttons">
                        <a href="https://wordpress.org/support/plugin/blog2social/reviews/" class="b2s-allow-rating" target="_blank">
                            <?php _e('Ok, you deserve it', 'blog2social'); ?>
                        </a>
                        <a href="#" class="b2s-hide-rating" target="_blank">
                            <?php _e('Nope, maybe later', 'blog2social'); ?>
                        </a>
                        <a href="#" class="b2s-hide-rating-forever" target="_blank">
                            <?php _e('I already did it', 'blog2social'); ?>
                        </a>
                    </p>
                </div>
            </div>
        <?php } ?>

        <!--Info-Trail-->
        <?php if (B2S_PLUGIN_USER_VERSION == 0 && !defined("B2S_PLUGIN_TRAIL_END") && !get_option('B2S_HIDE_PREMIUM_MESSAGE') && (isset($_GET['page']) && in_array($_GET['page'], array("blog2social", "blog2social-post", "blog2social-sched", "blog2social-publish", "blog2social-calendar")))) { ?>
            <div class="panel panel-group b2s-trail-premium-info-area b2s-notice">
                <div class="panel-body">
                    <div class="b2s-hide-premium-message b2s-close">x</div>
                    <h2 style="margin-top:0;font-size:20px;"><?php _e('Boost your social media automation with Blog2Social PREMIUM!', 'blog2social'); ?></h2>
                    <p>
                        <?php _e('Blog2Social provides even more options for auto-posting and auto-scheduling for your posts. Easily schedule your posts with the Best Time Scheduler or at your personal time settings. Post to multiple pages and groups. Select link post or image post formats for each network and post, select any image from your library and more.', 'blog2social'); ?>
                    </p>
                    <p class="b2s-notice-buttons">
                        <a data-toggle="modal" data-target="#b2s-trial-modal" href="#">
                            <?php _e('Yes, I want to test Blog2Social PREMIUM 30 days for free', 'blog2social'); ?>
                        </a>
                        <a href="#" class="b2s-hide-premium-message">
                            <?php _e("No, I'm happy with Blog2Social FREE", "blog2social"); ?>
                        </a>
                    </p>
                </div>
            </div>
        <?php } ?>

        <?php if (defined("B2S_PLUGIN_TRAIL_END") && strtotime(B2S_PLUGIN_TRAIL_END) > strtotime(gmdate('Y-m-d H:i:s')) && !get_option('B2S_HIDE_TRAIL_MESSAGE') && (isset($_GET['page']) && in_array($_GET['page'], array("blog2social", "blog2social-post", "blog2social-sched", "blog2social-publish", "blog2social-calendar")))) { ?>
            <div class="panel panel-group b2s-trail-premium-info-area b2s-notice">
                <div class="panel-body">
                    <div class="b2s-hide-trail-message b2s-close">x</div>
                    <h2 style="margin-top:0;font-size:20px;">
                        <?php _e('Your Blog2Social Premium Free Version is activated for ', 'blog2social'); ?>
                        <?php
                        $days = B2S_Util::getTrialRemainingDays(B2S_PLUGIN_TRAIL_END, date_default_timezone_get());
                        echo $days > 0 ? ("<span style='color:#79B232'>" . $days . "</span>" . __(' Days', 'blog2social')) : "<span style='color:#f33'>" . __(' today', 'blog2social') . "</span>";
                        ?>
                    </h2>
                    <p>
                        <?php echo _e('Blog2Social PREMIUM can do so much for you: Auto-publish your blog post on autopilot, automatically schedule your social media posts with the Best Time Manager. Select images and post formats (link post or image post) for each social community. Upload and select any image for sharing. Save multiple combinations of networks for different sharing purposes. Start from only $5.75 per month to benefit from PREMIUM features.', 'blog2social'); ?>
                    </p>
                    <p class="b2s-notice-buttons">
                        <a target="_blank" href="<?php echo B2S_Tools::getSupportLink('affiliate'); ?>"><?php _e('Upgrade to PREMIUM', 'blog2social'); ?></a>
                        <a href="#" class="b2s-hide-trail-message"><?php echo _e('I need some more time to decide', 'blog2social'); ?></a>
                    </p>
                </div>
            </div>
        <?php } ?>

        <?php if (defined("B2S_PLUGIN_TRAIL_END") && strtotime(B2S_PLUGIN_TRAIL_END) < strtotime(gmdate('Y-m-d H:i:s')) && !get_option('B2S_HIDE_TRAIL_ENDED') && (isset($_GET['page']) && in_array($_GET['page'], array("blog2social", "blog2social-post", "blog2social-sched", "blog2social-publish", "blog2social-calendar")))) { ?>
            <div class="panel panel-group b2s-trail-premium-info-area b2s-notice">
                <div class="panel-body">
                    <div class="b2s-hide-trail-ended-modal b2s-close">x</div>
                    <h2 style="margin-top:0;font-size:20px;">
                        <?php _e('Your free trial of Blog2Social PREMIUM has ended.', 'blog2social'); ?><br>
                        <?php _e('We hope you liked Blog2Social Premium.', 'blog2social'); ?>
                    </h2>
                    <p>
                        Blog2Social PREMIUM can do so much for you: Auto-publish your blog post on autopilot, automatically schedule your social media posts with the Best Time Manager. Select images and post formats (link post or image post) for each social community. Upload and select any image for sharing. Save multiple combinations of networks for different sharing purposes. Start from only $5.75 per month to benefit from PREMIUM features.
                    </p>
                    <p class="b2s-notice-buttons">
                        <a target="_blank" class="btn btn-sm btn-link" href="<?php echo B2S_Tools::getSupportLink('affiliate'); ?>"><?php _e('Yes, I want to upgrade now', 'blog2social'); ?></a>
                        <a href="#" class="btn btn-sm btn-link b2s-hide-trail-ended-modal"><?php _e('I need some more time to decide', 'blog2social'); ?></a>
                        <a href="#" class="btn btn-sm btn-link b2s-show-feedback-modal"><?php echo _e('Did you miss something? Tell us!', 'blog2social'); ?></a>
                    </p>
                </div>
            </div>
        <?php } ?>
    </div>
    <div class="col-md-3 del-padding-left hidden-xs hidden-sm">
        <?php
        $b2sLastVersion = get_option('b2s_plugin_version');
        if ($b2sLastVersion !== false) {
            echo '<span class="b2s-version-info pull-right">' . __('Version', 'blog2social') . ' ' . B2S_Util::getVersion($b2sLastVersion) . '</span>';
        }
        ?>
        <a target="_blank" href="https://www.blog2social.com">
            <img class="b2s-logo pull-right clear img-responsive" src="<?php echo plugins_url('/assets/images/b2s/b2s_logo.png', B2S_PLUGIN_FILE); ?>" alt="blog2social">
        </a>
    </div>
</div>
<div class="col-md-12 del-padding-left b2s-support-area hidden-md hidden-lg">
    <div class="col-md-9 del-padding-left">
        <a target="_blank" href="<?php echo B2S_Tools::getSupportLink('affiliate'); ?>" class="btn btn-success btn-block"><?php _e('Plans & Pricing', 'blog2social'); ?></a>
        <a target="_blank" href="<?php echo B2S_Tools::getSupportLink('faq'); ?>" class="btn btn-primary btn-block"> <?php _e('Support', 'blog2social'); ?></a>
    </div>
</div>
<!--Header-->


<!-- B2S-Trial -->
<div id="b2s-trial-modal" class="modal fade" role="dialog" aria-labelledby="b2s-trial-modal" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="b2s-modal-close close" data-modal-name="#b2s-trial-modal">&times;</button>
                <h4 class="modal-title"><?php _e('Test Blog2Social PREMIUM 30 days for free', 'blog2social'); ?></h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="alert alert-danger b2s-trail-modal-fail" style="display:none;">
                            <?php _e('The free trial can not be started. This blog has been already registered for the free trial.', 'blog2social'); ?>
                        </div>
                        <div class="form-group col-xs-12">
                            <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Social Media Auto-Posting', 'blog2social'); ?><br>
                            <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Post on pages and groups', 'blog2social'); ?><br>
                            <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Share on multiple accounts per network', 'blog2social'); ?><br>
                            <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Best Time Scheduler: Schedule once, multiple times or recurringly.', 'blog2social'); ?><br>
                            <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Reporting with links to all published social media posts', 'blog2social'); ?><br>
                        </div>
                        <div class="form-group col-xs-12">
                            <label for="trial_email"><?php _e('E-Mail', 'blog2social'); ?></label>
                            <input id="trial_email" class="form-control" type="email" value="<?php echo $wpUserData->user_email; ?>" name="trial_email">
                        </div>
                        <div class="form-group col-xs-12  col-md-6">
                            <label for="trial_vorname"><?php _e('First Name', 'blog2social'); ?></label>
                            <input id="trial_vorname" class="form-control" type="text" value="<?php echo $wpUserData->user_firstname; ?>" name="trial_vorname">
                        </div>
                        <div class="form-group col-xs-12  col-md-6">
                            <label for="trial_nachname"><?php _e('Last Name', 'blog2social'); ?></label>
                            <input id="trial_nachname" class="form-control" type="text" value="<?php echo $wpUserData->user_lastname; ?>" name="trial_nachname">
                        </div>
                        <div class="col-xs-12">
                            <p><?php _e("By creating an account, you agree to Blog2Social's <a target=\"_blank\" href=\"https://www.blog2social.com/en/terms/\">Conditions of Use</a> and <a target=\"_blank\" href=\"https://www.blog2social.com/en/privacy/\">Privacy Notice</a>.", "blog2social") ?></p>
                            <br>
                        </div>
                        <div class="col-xs-12">
                            <div class="pull-left">
                                <span class="glyphicon glyphicon-info-sign glyphicon-primary"></span>  <?php _e('No credit card required', 'blog2social'); ?>
                            </div>
                            <div class="pull-right">
                                <input type="hidden" name="trial_url" id="trial_url" value="<?php echo get_option('home'); ?>" />
                                <input class="btn btn-success pull-right b2s-trail-btn-start" type="submit" value="<?php _e('Get Started', 'blog2social'); ?>">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- B2S-Key-Info-->
<div class="modal fade" id="b2sInfoKeyModal" tabindex="-1" role="dialog" aria-labelledby="b2sInfoKeyModal" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <!--Info-Key-->
                <div class="b2s-key-area-success" style="display: none;">
                    <div class="col-md-12 text-center b2s-text-xl">
                        <?php _e("Thank you for choosing Blog2Social Premium.", "blog2social"); ?>
                    </div>
                    <div class="clearfix"></div>
                    <br>
                    <div class="col-md-12 text-center">
                        <div class="col-md-4">
                            <span class="glyphicon glyphicon-ok b2s-glyphicon-xl glyphicon-success"></span>
                        </div>
                        <div class="col-md-8 b2s-text-xl">
                            <?php _e("Your license", "blog2social"); ?><br>
                            <span class="b2s-color-green b2s-text-bold"><?php _e('Blog2Social Premium', 'blog2social'); ?></span> <span class="b2s-key-area-key-name b2s-color-green b2s-text-bold"></span> <br><?php _e('has been successfully activated.', 'blog2social'); ?>
                        </div>
                    </div>
                </div>
                <div class="b2s-key-area-fail" style="display: none;">
                    <div class="col-md-12 text-center">
                        <div class="col-md-4">
                            <span class="glyphicon glyphicon-remove b2s-glyphicon-xl glyphicon-danger"></span>
                        </div>
                        <div class="col-md-8 b2s-text-xl">
                            <?php _e('Your entered License Key is invalid. Please contact support!', 'blog2social'); ?>
                        </div>
                    </div>
                </div>
                <div class="b2s-key-area-fail-max-use" style="display: none;">
                    <div class="col-md-12 text-center">
                        <div class="col-md-4">
                            <span class="glyphicon glyphicon-remove b2s-glyphicon-xl glyphicon-danger"></span>
                        </div>
                        <div class="col-md-8 b2s-text-xl">
                            <?php _e('Your license key has reached the maximum number of users.', 'blog2social'); ?>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <br>
                <div class="text-center">
                    <button type="button" class="b2s-modal-close btn btn-primary" data-modal-name="#b2sInfoKeyModal" aria-label="Close"><?php _e("OK", "blog2social"); ?></button>
                </div>
            </div>
        </div>
    </div>
</div>


<input id="b2sUserAcceptPrivacyPolicy" type="hidden" value="<?php echo (($showPrivacyPolicy) ? 'true' : 'false'); ?>">
<!-- B2S-Privacy-Policy-Info-->
<div class="modal fade" id="b2sModalPrivacyPolicy" tabindex="-1" role="dialog" aria-labelledby="b2sModalPrivacyPolicy" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog b2s-scroll-modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"> <img src="<?php echo plugins_url('/assets/images/b2s@32.png', B2S_PLUGIN_FILE); ?>" alt="blog2social"> <?php _e('We updated our Privacy Policy', 'blog2social') ?></h4>
            </div>
            <div class="modal-body b2s-scroll-modal-body b2s-modal-privacy-policy-scroll-content">
                <p>
                    <?php
                    if ($b2sPrivacyPolicy !== false) {
                        echo utf8_encode($b2sPrivacyPolicy);
                    }
                    ?> 
                </p>
            </div>
            <div class="modal-footer">
                <a href="#" class="b2s-scroll-modal-down" address="true"></a>
                <br>
                <div class="pull-left btn-padding"><?php _e('Blog2Social is a service of Adenion GmbH', 'blog2social'); ?></div>
                <button class="btn btn-success b2s-modal-privacy-policy-accept-btn"><?php _e('I agree to the Adenion Privacy Policy', 'blog2social'); ?></button>
                <section class="b2s-scroll-modal-end"></section>
            </div>
        </div>
    </div>
</div>

