<div class="col-md-3 del-padding-left b2s-support-area hidden-xs hidden-sm">
    <a target="_blank" href="<?php echo B2S_Tools::getSupportLink('affiliate'); ?>" class="btn btn-success btn-block"><?php _e('Plans & Pricing', 'blog2social') ?></a>
    <a target="_blank" href="<?php echo B2S_Tools::getSupportLink('faq'); ?>" class="btn btn-primary btn-block"><?php _e('Support', 'blog2social') ?></a>
    <a target="_blank" href="<?php echo B2S_Tools::getSupportLink('howto'); ?>" class="btn btn-success btn-block"><?php _e('How to work with Blog2Social', 'blog2social') ?></a>
</div>
